services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: churn-api
    ports:
      - "8000:8000"
    volumes:
      - ./App:/app/app
      - ./Model:/app/model
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: churn-frontend
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
    volumes:
      - ./streamlit_app.py:/app/streamlit_app.py
    depends_on:
      - api
    restart: unless-stopped
